### ISSUE TITLE
Mengenangaben pro Attribut

### ISSUE THREAD

**Issue by Anton2024tf** [zencartpro/157-modul-dpu#1]
Hallo, 
ich hab 1.5.7g installiert und ua. das dpu Modul und dann festgestellt, dass es keine Möglichkeit gibt, die Mengenangaben für die einzlenen Attrribute einzugeben. Oder finde ich es nur nicht?
Es gab ja auch das Modul Stock by Attributes für 1.5.6. Funktioniert das auch für 1.5.7.g? 
Da ich meinen alten Shop updaten möchte und damals Stock by Attributes drin hatte, wäre auch die Frage, ob das dann geht oder ob ich die Artikel mit Attributen rausnehmen müsste.
Ich hoffe, das ist ok, das hier zu fragen. Ist ja keine Fehlermeldung an sich, wäre aber schön, Mengenangaben bei Attributen machen zu können.
Viele Grüße
Anton

**Comment by webchills** [comment]
Mengenangaben für Attribute haben nichts mit dem DPU Modul und auch nichts mit dem Stock by Attributes Modul zu tun. Wenn Du eine solche Funktion im Shop hattest, dann vermutlich durch irgendein amerikanisches Zusatzmodul wie z.B. Attribute Grid. Da kannst Du schauen, ob es da etwas Aktuelles gibt und es selbst anpassen. oder anpassen lassen.
Das alte Modul Lagerbestand für Artikel mit Attribute (Stock by Attributes) für 1.5.6 funktioniert so keinesfalls in 1.5.7. Eine für 1.5.7g/1.5.7h aktualisierte Version wird es nach dem Launch von 1.5.7h voraussichtlich Anfang April geben, behalte einfach das entsprechende Repository https://github.com/zencartpro/157-modul-stock-by-attributes im Auge.

**Comment by Anton2024tf** [comment]
Da hab ich mich oben missverständlich ausgedrückt. Stock by Attributes ermöglicht laut Beschreibung das Anlegen von Lagerbeständen für Artikel mit Attributen. Das meinte ich.
Dann schaue ich gern Anfang April nach der aktualisierten Version davon und hoffe, dass das Update der Datenbank vorher trotzdem funktioniert. Falls Du dazu einen Tipp hast, was die Lagerbestände der Attribute in der Datenbank angeht, dann sehr gerne. Ansonsten probiere ich es einfach mal aus.
Danke Dir!

**Comment by webchills** [comment]
Ich dachte Du meinst, dass der Kunde im Frontend beim Artikel Mengen für das gewünschte Attribut eingeben kann. 

Das neue Stock by Attributes für 1.5.7 verwendet die bisherigen Lagerbestände in der Datenbank weiter, die gehen bei einem Update natürlich nicht verloren und müssen auch nicht irgendwie aktualisiert werden.

**Comment by Anton2024tf** [comment]
Ok, super. Dankeschön! Dann mach ich nächste Woche das Update und füge das neue Stock by Attributes später hinzu, wenn es da ist.

**Comment by webchills** [comment]
Wenn Du vorhast einen 1.5.6 auf 1.5.7 zu aktualisieren, dann nimm dazu dann gleich die 1.5.7h, die ca. am 29.3. released wird. Nicht die aktuelle Release 1.5.7g. Kannst Dir ja mal die 1.5.7h installieren und anschauen (Download über den Code Button auf https://github.com/zencartpro/zencart-german-grundsystem). Damit bist Du dann wirklich auf dem neuesten Stand und kannst auch PHP 8.2 verwenden.

**Comment by Anton2024tf** [comment]
Hm... ich wollte das zum Monatsende fertig bekommen, weil Sofortüberweisung mir gekündigt hat (da ich nicht genug Umsatz mache) und Paypal Express in meiner alten Version (1.5.5f) nicht funktioniert. Es gab da mal ein Patch von Dir, aber da hab ich nur Links zu gefunden, die ins Leere führen. Aber falls Du den noch irgendwo hast, könnte ich das versuchen und hätte mehr Zeit für die neue Version.
Dh Du nimmst bis zum 29.3. noch Änderungen vor ja? 
Ich bin halt etwas langsam beim Installieren der Module und verschiedener Einstellungen, die ja teils auch im Code vorzunehmen sind und auch weil ich - was die Sprachdateien und andere Änderungen von mir angeht - mit meinen alten Dateien vergleichen muss. Also ich bekomm das schon hin, aber nicht innerhalb von 2-3 Tagen :).
Daher wäre der Patch vielleicht ganz gut und dann könnte ich in Ruhe 1.5.7h installieren. Hast Du den noch?

**Comment by webchills** [comment]
Du kannst den aktuellen Stand der 1.5.7h verwenden, da wird sich nicht mehr viel ändern. Schau, dass dieser uralte 1.5.5 so schnell wie möglich aus dem Netz verschwindet, das ist ja gemeingefährlich.
Hier ist das PayPal Express Update von damals, kannst es gerne übergangsweise im jetzigen 1.5.5 probieren und wenns damit funktioniert hast Du mehr Zeit für das Update:
[PayPal Express Update fuer Zen Cart 1.5.5f deutsch.zip](https://github.com/zencartpro/157-modul-dpu/files/14669073/PayPal.Express.Update.fuer.Zen.Cart.1.5.5f.deutsch.zip)

**Comment by Anton2024tf** [comment]
Ui, danke Dir!!

**Comment by Anton2024tf** [comment]
Noch eine kurze Frage zum Paypal Update für 1.5.5f , wenn das ok ist: Bei dem Express Checkout Button wird der netto-Wert übergeben. Lässt sich das ändern? Oder alternativ: wenn ich PayPal über den Radio-Button unter Zahloptionen auswähle, komme ich zwar nach Klick auf Kaufen zu Paypal und dann zurück zum Shop, muss aber am Ende nochmal auf Kaufen klicken, um die Bestellung abzuschließen. Das ist sehr verwirrend und dürfte zu Bestellabbrüchen führen. Gab es da eine Lösung für? Bisher hab ich keine im Forum gefunden.
Es wäre toll, das noch hinzukriegen, weil ich zwar mit 157h angefangen habe, aber es noch eine Weile dauern wird, bis ich alle Module und alles Weitere eingerichtet habe.
Lieben Dank!

**Comment by webchills** [comment]
@ Netto Wert
Ist korrekt so, weil an dieser Stelle noch nichts über die Steuern bekannt ist, da das Lieferland noch nicht feststeht

@ Rückleitung
Ist kein Fehler sondern bewusst so, siehe hier unter Ablauf in Zen Cart
https://www.zen-cart-pro.at/knowledgebase/konfiguration-von-paypal/
In einer aktuellen Zen Cart Version erscheinen entsprechende Hinweistexte für den Kunden, es führt nicht zu Abbrüchen, da dort genau steht, wie der Ablauf ist.
In einer 1.5.5 Installation gibt es diese Texte natürlich nicht.
1.5.5 ist weit jenseits aller Supportgrenzen und sollte seit Jahren nicht mehr eingesetzt werden, da wirst Du für den Übergang ohne diese Texte leben müssen. Schließe diesen "Issue" jetzt, hat nichts mehr mit DPU oder Sonstigem zu tun.

**Comment by Anton2024tf** [comment]
Danke, dass Du nochmal geantwortet hast! Das weiß ich sehr zu schätzen und baue mir jetzt einen Text ein.
